### ISSUE TITLE
Edge to edge UI issue on Android 15

### ISSUE THREAD

**Issue by VTimisica** [refiner-io/mobile-sdk-android#16]
There is an UI error on devices that run Android 15, probably related to the [edge-to-edge enforcement](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge). Here is a screenshot with a test survey:

![Screenshot from 2024-11-01 12-54-47](https://github.com/user-attachments/assets/3f668238-2aa3-46b1-863b-90de2c1a1315)

**Comment by tekinalper** [comment]
@VTimisica Thanks for letting us know. We'll check and plan a fix for this.

**Comment by tekinalper** [comment]
Hi @VTimisica @michal-luszczuk I just released an alpha version to support edge-to-edge display for API level >= 35. Could you please test "1.5.3-alpha01" and let me know if it fixes the issue? I also did several tests with lower API level devices. After your confirmation, I'll release it in stable channel.

**Comment by VTimisica** [comment]
Hi. Thank you for the fix!
The bottom sheet looks fine, but the content of the screen it's covered right now. Is this intended?

<img width="400" alt="image" src="https://github.com/user-attachments/assets/36547885-b9c8-404a-b928-3f3b25d0eb9b">

**Comment by tekinalper** [comment]
@VTimisica Opps, it was by mistake. Thank you for letting me know. Here is the new version "1.5.3-alpha02".

**Comment by VTimisica** [comment]
Seems like `1.5.3-alpha02` is not released yet. "Could not find io.refiner:refiner:1.5.3-alpha02"

**Comment by tekinalper** [comment]
@VTimisica It should be available now/in couple of minutes, there was a deployment error.

**Comment by tekinalper** [comment]
@VTimisica Did you have a chance to test the version?

**Comment by tekinalper** [comment]
Version [1.5.3](https://github.com/refiner-io/mobile-sdk-android/releases/tag/1.5.3) is released.
