### ISSUE TITLE
Version 1.3.8 available on mavenCentral but no changelog available

### ISSUE THREAD

**Issue by michal-luszczuk** [refiner-io/mobile-sdk-android#7]
Version 1.3.8 was released https://mvnrepository.com/artifact/io.refiner/refiner/1.3.8
But there is no information what this version brings, no changelog, no information in the Github 'releases'.

What can we do to get this info?

**Comment by tekinalper** [comment]
Hi, we've forgot to publish a new release in releases section, so sorry for that! 
Here it is: https://github.com/refiner-io/mobile-sdk-android/releases/tag/1.3.8
